-- database/init.sql
CREATE TABLE IF NOT EXISTS Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(100) NOT NULL UNIQUE,
  Password NVARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PlaylistClicks (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  PlaylistName NVARCHAR(200) NOT NULL,
  Count INT NOT NULL DEFAULT 0
);
